export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DEL_ITEM_FROM_CART = 'DEL_ITEM_FROM_CART';
export const GET_CART = 'GET_CART';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';